tinyMCE.addI18n('ja.advanced',{
style_select:"スタイル",
font_size:"フォントサイズ",
fontdefault:"フォントファミリ",
block:"フォーマット",
paragraph:"段落(p)",
div:"ブロック(div)",
address:"アドレス(address)",
pre:"整形済み(pre)",
h1:"見出し 1(h1)",
h2:"見出し 2(h2)",
h3:"見出し 3(h3)",
h4:"見出し 4(h4)",
h5:"見出し 5(h5)",
h6:"見出し 6(h6)",
blockquote:"引用文(blockquote)",
code:"コード(code)",
samp:"サンプルコード(samp)",
dt:"定義語(dt)",
dd:"定義説明(dd)",
span:"Span",
bold_desc:"太字 (Ctrl+B)",
italic_desc:"斜体 (Ctrl+I)",
underline_desc:"下線 (Ctrl+U)",
striketrough_desc:"取消線",
justifyleft_desc:"左揃え",
justifycenter_desc:"中央揃え",
justifyright_desc:"右揃え",
justifyfull_desc:"両端揃え",
bullist_desc:"順序なしリスト",
numlist_desc:"順序付きリスト",
outdent_desc:"字下げ解除",
indent_desc:"字下げ",
undo_desc:"元に戻す (Ctrl+Z)",
redo_desc:"やり直し (Ctrl+Y)",
link_desc:"リンクを挿入/編集",
unlink_desc:"リンク解除",
image_desc:"イメージを挿入/編集",
cleanup_desc:"コードのクリーンアップ",
code_desc:"HTMLソースを編集",
sub_desc:"下付き文字",
sup_desc:"上付き文字",
hr_desc:"水平線を挿入",
removeformat_desc:"フォーマット削除",
custom1_desc:"カスタム説明はここへ",
forecolor_desc:"テキスト色を選択",
backcolor_desc:"背景色を選択",
charmap_desc:"特殊文字を挿入",
visualaid_desc:"ガイドライン表示/非表示切り替え",
anchor_desc:"アンカーを挿入/編集",
cut_desc:"切り取り",
copy_desc:"コピー",
paste_desc:"貼り付け",
image_props_desc:"イメージプロパティ",
newdocument_desc:"新規ドキュメント",
help_desc:"ヘルプ",
blockquote_desc:"引用文",
clipboard_msg:"コピー/切り取り/貼り付けは、MozillaおよびFirefoxでは利用できません。\r\nこの問題について詳しい情報が必要ですか？",
path:"パス",
newdocument:"内容を全てクリアしてもよろしいですか？",
toolbar_focus:"ツールバーへのジャンプ - Alt+Q, エディタへジャンプ - Alt-Z, 要素のパスへジャンプ - Alt-X",
more_colors:"その他の色",
shortcuts_desc:'アクセシビリティのヘルプ',
help_shortcut:'. ツールバーの場合はALT F10を押して下さい。ヘルプは ALT 0 を押して下さい。',
rich_text_area:"リッチテキストエリア",
toolbar:"ツールバー"
});
